#!/bin/bash

echo 'installing jupyter'
cd /tmp
git clone https://github.com/slowenthal/cql_kernel/
cd /tmp/cql_kernel
git checkout cstar3
#apt-get install -y python-pip gcc python-dev
sleep 120
export PATH=/usr/local/bin:/usr/bin:$PATH
pip install --upgrade pip
/usr/local/bin/pip install --upgrade six
/usr/local/bin/pip install jupyter
/usr/local/bin/pip install jupyter_client
/usr/local/bin/pip install ipython
/usr/local/bin/pip install cql_kernel
/usr/local/bin/pip install cassandra-driver
cd /tmp/cql_kernel/cql_kernel
python install.py node0
