#!/bin/bash

echo 'Starting Notebooks'
wget -O /tmp/start_notebooks.sh https://gist.githubusercontent.com/weideng1/cc3ae8bd048537d4f12edef5b663259f/raw/2fa95ea8da14d39fadbb343bc7918fb7e462e5f2/start_notebooks.sh
bash /tmp/start_notebooks.sh
